executable              = ttZ-rivet.sh
arguments               = $(myfile)
output                  = output/batch_run_job.$(ClusterId).$(ProcId).out
error                   = error/batch_run_job.$(ClusterId).$(ProcId).err
log                     = log/batch_run_job.$(ClusterId).$(ProcId).log
+JobFlavour             = "workday"
transfer_output_remaps  = "TTZToLLNuNu.yoda=rivet_output/TTZToLLNuNu.$(ClusterId).$(ProcId).yoda"
queue myfile from TTZToLLNuNu_fileList.txt
